### ISSUE TITLE
RFC: openlab CLI

### ISSUE THREAD

**Issue by NiklasTR** [labdao/openlab-cli#1]

**Comment by NiklasTR** [comment]
I think having a lightweight CLI is an important building block for release openlab v0

**Comment by blahah** [comment]
Agreed - just moving the spec from the README so I can push the code I've been working on:

## Spec (moved from initial README)

A basic CLI that encompasses the following functions: 
* lab login - prompts the deposition of an estuary API key and public wallet address
* lab file push dir/file - returns hash of uploaded file after calling estuary
* lab file pull dir/file - returns hash of downloaded file after calling estuary
* lab file ls - lists uploaded files and files that have been sent to the wallet address as NFTs
* lab service ls - lists available services and jobs that have been triggered
* lab service push dir/file.json 0x...42 - submits a job and triggers the signing of a transaction with metamask
* lab service pull service_name - downloads a json template for the service metadata json

**Comment by NiklasTR** [comment]
awesome!

**Comment by NiklasTR** [comment]
apps = service

openlab service list
service name, service id, provider name, provider id, price, rating

**Comment by NiklasTR** [comment]
openlab app name --example - JSON template
openlab app name  - specs for the app with links to documentation

**Comment by NiklasTR** [comment]
openlab job submit job.json 
openlab job status - job id, application id, timestamp etc. , IPFS CID for finished jobs and log data

states include:
posted
accepted / rejected
queued 
running
completed / failed
transferred (NFT was sent)

**Comment by NiklasTR** [comment]
openlab job log "job id" - reach feature that gives log

**Comment by NiklasTR** [comment]
openlab token mint jobid, metadataCID, logCID, fileCID

the jobID is an IPFS CID that is generated after uploading an input job description and automatic addition of UUID 
open token mint is basically linking to a directoryCID - 4 files (as described above)

**Comment by NiklasTR** [comment]
openlab token transfer

openlab transaction claim
openlab transaction pay

more functions to rate provider etc.

**Comment by NiklasTR** [comment]
openlab provider blame :D 

reputation system for useful job requests

**Comment by blahah** [comment]
Closing for posterity
