### ISSUE TITLE
feature: download progress reporting

### ISSUE THREAD

**Issue by NiklasTR** [labdao/openlab-cli#11]
link to the loom:
https://www.loom.com/share/e167061806cf43449aa169d3bab67a86

two potential features for the backlog
perhaps we could add a knob to run the download process in the background. 
An alternative feature could be a progress bar

**Comment by blahah** [comment]
download progress bars are implemented https://github.com/labdao/openlab-cli/blob/f9b4e08e25d01f5ddaf1ffbd1d55bf691783a33e/src/commands/file/pull.ts#L45:L66

running downloads in the background should be a new issue if necessary
