### ISSUE TITLE
RFC: operations including contract interactions

### ISSUE THREAD

**Issue by NiklasTR** [labdao/openlab-cli#12]
-- openlab job submit -- 
input:
user wallet address - 0x
provider wallet address - 0x
token amount - gwei
jobdefinition.json - URI

return:
UUID = hash(user wallet, provider wallet, timestamp)

contract action:
deposit stuff in escrow

-- openlab job status UUID -- 
#1 - has more details
off-chain process that pings the registered providers address and gives an update about the job status

**Comment by NiklasTR** [comment]
loose thoughts>
1) iniiate tx {clinetkey, serverkey, uri_descriptor, token_eth}
that fx pays into the escrow 
2) server listents to the contract and goes to work
3) NFT with the work gets send to client
4) server requests release from escrow / client auto-confirms
clinet = customer
server = provider
greenlist with trusted wallets (greenlist providers, and greenlist for consumers)
user rating - off-chain using tools like ceramic
openlab.run
list all services
template JSON, wallet address, name
openlab job status
open job submit (.json, 10ETH, provider address)

**Comment by NiklasTR** [comment]
-- openlab token mint --
mints token ipfs - rel trivial

-- openlab token transfer -- 
in v1 can include synchronous transfer of escrow and NFT transfer

-- openlab job claim --
* backlog*
is it 3d past openlab token transfer? NO -> failure ; YES -> drain the escrow

-- openlab job blame --
*backlog* 
client - within the 3d? YES - arbitration triggered (**backlog**)

**Comment by NiklasTR** [comment]
initial version with 3 functions deployed rinkeby

**Comment by blahah** [comment]
Archiving for posterity. The exchange, contract and graph operations now live in the `openlab job` subcommand, as implemented excruciatingly in #33
