### ISSUE TITLE
openlab app list with native integration of nf-core

### ISSUE THREAD

**Issue by NiklasTR** [labdao/openlab-cli#24]
calling the list of services within openlab could take a lot of inspiration from the  nf-core library: 
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/18559148/158357338-84235e9f-cf42-430d-ae2a-fd6c05955cc4.png">

Given that we want to build on the nf-core standard, I would suggest we even use a green font for all services that are open source and adhere to nf-core specifications. 
There could be other color codes in the future, too: 
* non-profit community contributor
* for-profit community contributor
* non-profit
* for-profit
* unknown

**Comment by blahah** [comment]
closing because it is duplicated by #37
