### ISSUE TITLE
within openlab account add, send 0.5 testnet MATIC to the newly created address 

### ISSUE THREAD

**Issue by NiklasTR** [labdao/openlab-cli#32]
- can we work with polygon team here?

**Comment by acashmoney** [comment]
@NiklasTR initial thought is this would be difficult to implement. We'd need a way to maintain our own steady supply of MATIC from the faucet (which could get us rate-limited) and listen to account creation happening on the CLI. Then initiate a transfer transaction from our supply of MATIC test to the newly created address.

@tohrnii thoughts?

**Comment by tohrnii** [comment]
Yeah automating this does require a lot of overhead (we'll need to do our own rate-limiting for ex even if we can get polygon team to give us a large number of test MATIC tokens). This will most likely have to be a manual process imo.

**Comment by blahah** [comment]
It was straightforward to implement using the MATIC faucet, and is now an interactive option during wallet creation with `openlab account add`

https://github.com/labdao/openlab-cli/blob/f9b4e08e25d01f5ddaf1ffbd1d55bf691783a33e/src/commands/account/add.ts#L51:L68
