### ISSUE TITLE
a server.py / server.R / server.sh script to query open jobs and steer the local compute infrastructure 

### ISSUE THREAD

**Issue by NiklasTR** [labdao/openlab-cli#36]
```
# loading some general purpose packages
library(tidyverse)
library(rjson)

# list all jobs
system("bin/dev job list --csv > openjob.csv")
# filter open jobs that have a complete URI
jobs = read_csv("openjob.csv", skip = 4) %>% filter(Status == "open") %>% 
  mutate(nchar = nchar(Joburi)) %>% 
  filter(nchar == 46)


if(nrow(jobs) > 0){
  # if there is an open job, pull the jobURI to learn more
  jobs <- jobs %>%
    mutate(job_out = paste0("tickets/", Joburi, ".json")) %>%
    mutate(command = paste0("bin/dev file pull ", Joburi, " -o ", job_out)) %>% 
    #head(1) %>% 
    rowwise() %>%
    mutate(json_status = system(command)) 
  
  # extract job description
  jobs_content <- jobs %>% 
    rowwise() %>%
    mutate(json = list(rjson::fromJSON(file = job_out))) %>% 
    mutate(service = .$json[[1]]$attributes[[2]]$value,
           input = .$json[[1]]$attributes[[3]]$value) %>% 
    # if jobs of the "lab-reverse_complement" class exist, claim and run the job
  if(jobs_content %>% filter(service =="lab-reverse_complement") %>% nrow() > 0){
    # TODO claim the job
    # TODO something like system(paste0("bin/dev job accept ", Id))
    # TODO needs password input for accpeting jobs
    # run the job
    jobs_content %>% filter(service =="lab-reverse_complement")  %>% 
      rowwise() %>%
      mutate(response = list(httr::GET(url = paste0("https://02wun6.deta.dev/", input)))) %>% 
      mutate(output = content(response)$reverse_complement)
    
    # TODO format a response JSON
    # TODO pin the response JSON to IPFS 
    # TODO call the swap function to mint the NFT and get the reward
  }
}

# TODO implement loop over these operations to regularly check for open jobs, filter them, claim them and return the result via the exchange.
````

**Comment by NiklasTR** [comment]
We have a basic version of the exchange protocol running on the "cli-subgraph-a" branch

The next step is now to automate the server side of the transaction to automatically check for open jobs, filter them, claim them and return results.

@yawnxz has been working on a version of this in the past and I created an ugly script today in R that can handle parts of the server side when run in the working dir of the openlab-cli

I would love if someone could take this (pseudo)code and and implement a "server.R" / "server.py" script that could be run in perpetuity on the server side to automatically look for new jobs and process them
@blahah , @mahdi and @Science.Stanley this is very much the kind of script that would run on the head node of a cluster, with the head node submitting jobs to the cluster if they adhere to a certain logic
This is spagetthi code, and should be factored into separate functions (e.g. filter, process, submit)

**Comment by science** [comment]
Hello, you included me in this post, but I think you meant to include someone else -- just FYI that the intended person will not get notified..

**Comment by NiklasTR** [comment]
Oh hi - thank you for the heads-up -> namespace collision between discord and github!

**Comment by blahah** [comment]
OK, I'm closing this and we can create a new issue if there's a feature of the CLI being requested.
